// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var RavenJs = require("raven-js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var Internal = /* module */[];

function config(dsn, config$1, param) {
  if (config$1 !== undefined) {
    return RavenJs.config(dsn, Caml_option.valFromOption(config$1));
  } else {
    return RavenJs.config(dsn);
  }
}

exports.Internal = Internal;
exports.config = config;
/* raven-js Not a pure module */
